
version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./awake:/awake
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=awake
      - DB_USER=postgres
      - DB_PASS=root
    depends_on:
      - dbb


  dbb:
    image: postgres
    ports:
      - 9122:5432
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=awake
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root